do_api_token: "{{ lookup('file', '~/.ssh/do/my.apikey') }}"
pubkeyid: 23550519
wait_minutes:  4     # max time to create VM, usually it's under 2 minutes
wait_ssh:     25     # max wait for SSH to come up
