random_string: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,punctuation') }}"
repo_list:
  - "deb http://packages.dotdeb.org     jessie all  # nginx"
  - "deb https://packages.sury.org/php/ jessie main # php5.6"
  - "deb [arch=amd64] http://lon1.mirrors.digitalocean.com/mariadb/repo/10.1/debian jessie main"
repo_keys:
  - 7E3F070089DF5277 # www.dotdeb.org/dotdeb.gpg
  - AC0E47584A7A714D # packages.sury.org/php/apt.gpg
  - CBCB082A1BB943DB # package-signing-key@mariadb.org
emp_pkgs:
  - nginx-light
  - php5.6-fpm
  - php5.6-mysql
  - mariadb-server-10.1
