- hosts: localhost
  gather_facts: no
# vars:
#   ts1: 20190303181418Z
#   iso8601: 2019-03-31T14:40:04Z
  tasks:
    - debug: msg="{{ _|nowZ }}"
    # debug: msg="{{ ansible_date_time.iso8601 }}"
    - name: Get current certificate if any
      get_certificate:
        host: y.d35.ru
        port: 443
      delegate_to: localhost
      run_once: true
      ignore_errors: yes
      register: cert

    - name: Check current certificate validity for the next 30 days
      set_fact:
        renew_cert: yes
      delegate_to: localhost
      when: cert.failed or (cert.not_after|to_datetime('%Y%m%d%H%M%SZ') - _|nowZ|to_datetime('%Y%m%d%H%M%SZ')).total_seconds() <  30*24*3600
    - debug: msg="Renew"
      when: renew_cert|bool

#   - tempfile:
#     register: f0
#   - debug: msg="{{ f0.path }}"
#   - stat: path={{ f0.path }}
#     register: f0
#   - set_fact: t0={{ f0.stat.mtime }}
#   - debug: var=f0
#   - file: path="{{ f0.stat.path }}" state=touch
#   - stat: path={{ f0.stat.path }}
#     register: f0
#   - debug: msg="{{ f0.stat.mtime - t0|float }}"
