- hosts: provisioner
  gather_facts: no
  vars_files:
    - vars/do1.yml
  tasks:
    - name: Gather facts about SSH key (fingerprint look-up)
      shell: "echo {{ root_ssh_pk }} | cut -f2 -d' ' | base64 -d | md5sum -b | sed 's/../&:/g; s/: .*$//'"
      register: cmd_res
      changed_when: no
    - set_fact: kfprint="{{ cmd_res.stdout }}"

    - digital_ocean_sshkey_facts: oauth_token={{ do_api_token }}
      register: do_keys

    - set_fact: pubkeyid={{ item.id }} pubkeyn={{ item.name }}
      loop: "{{ ssh_keys|json_query(pk) }}"
      vars:
        pk: "[?fingerprint=='{{ kfprint }}']"

  # - debug: msg="SSH key {{ kfprint }} found, id={{ pubkeyid }}, name={{ pubkeyn }}"

    - name: Find or create Droplet, then register in-memory
      digital_ocean_droplet: # FIXME auto-add host key on the 1st connection
        state: present
        name: "{{ vm_name }}"
        region_id: "{{ dc }}"
        size_id: "{{ size }}"
        image:  "{{ image }}"
        ssh_keys: "{{ pubkeyid }}"
        unique_name: yes
        ipv6: "{{ needIPv6 }}"
        private_networking: no
        oauth_token: "{{ do_api_token }}"
        wait_timeout: "{{wait_minutes * 60}}" # wait for DO response, default is 120
      register: vm

    - debug: msg="Droplet {{vm_name}} {{vm.data.ip_address}} {{vm.data.ipv6_address | default('-')}}"

    - name: Add droplet to in-memory (dynamic) inventory
      add_host:
        name: do1
        groups: dohosts
        ansible_host: "{{ vm.data.ip_address }}"
        ansible_user: root
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=accept-new' # need OpenSSH >= 7.6
      changed_when: false

- hosts: dohosts #TODO ensure StrictHostKeyChecking=yes
  gather_facts: no
  vars_files:
    - vars/main.yml
    - vars/do1.yml  # TODO: split in two, leave only host-specifics, strip DO details!
    - vars/trim0-do.yml
    - vars/emp.yml

  tasks:
    - include: tasks/sysvinit.yml
    - include: tasks/ssh-port.yml
    - include: tasks/swap.yml
    - include: tasks/software.yml
    - include: tasks/security.yml
    - include: tasks/users.yml
    - include: tasks/trim.yml
    - debug: var=uninstall.stdout_lines
    - include: tasks/add-srv.yml

  handlers:
    - include: handlers/site.yml
