- hosts: provisioner
  gather_facts: no
  vars_files:
    group_vars/digitalocean.yml
  vars:
    vm_provider: digitalocean
    state: pristine
    wait_minutes: 4
  # do_api_token:
    pubkeyid: 23550519  # keyID known to DO
    dc: fra1            # ams[23], lon1; blr1 IN, sgp1 SG; nyc[123], sfo[12], tor1.
    vm_name: de.x302.net  # DO sets PTR for IPv4 and IPv6 addresses if it's FQDN
    size:  s-1vcpu-1gb  # s-1vcpu-2gb, s-2vcpu-2gb, s-1vcpu-3gb, ..., s-32vcpu-192gb.
  # image: debian-8-x64  # fedora-27-x64, freebsd-11-1-x64-zfs, ubuntu-14-04-x64-do, ...
    needIPv6: yes
    private_net: no
    # ssh_set_port: 2222  # role default: 2222

  roles:
    - um  # set_fact: um

  tasks:
    - debug: var=um
    - debug: msg="Droplet {{um.droplet.name}} {{um.ip4}} {{um.ip6 | default('-')}}"
