- hosts: localhost
  gather_facts: no
  tasks:
    - add_host:
        name: s1
        ansible_port: 2222
        vm:
          cloud: digitalocean
          dc: fra1
          name: s1.example.com
          size:  s-1vcpu-1gb
          image: debian-8-x64
          private_net: yes
          doIPv6: yes
    # register: t1
    # debug: var=t1
- hosts: s1
  gather_facts: no
  tasks:
    # debug: msg="Boo!"
    # delegate_to: localhost
    - include_role: name=exactpro.um
      vars:
        do_api_token: "{{ lookup('file', '~/.ssh/do/my.apikey') }}"
        pubkeyid: 23550519
        wait_minutes:  4     # max time to create VM, usually it's under 2 minutes
        wait_ssh:     25     # max wait for SSH to come up
        state: pristine
      register: m1
    # debug: var=vm
    - debug: msg="Host {{ inventory_hostname }} {{ ansible_host }}:{{ ansible_port }}"
