#https://docs.ansible.com/ansible/latest/modules/acme_account_facts_module.html

# ln -s i\
#   ~/dehydrated/accounts/aHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2RpcmVjdG9yeQo/account_key.pem \
#   ~/.ssh/le-33935398.key

- hosts: localhost
  gather_facts: no
  vars:
    acme_account_key_src: '~/.ssh/le-33935398.key'
  tasks:
    - include: tasks/acme-facts-kfile.yml
