#https://docs.ansible.com/ansible/latest/modules/acme_account_facts_module.html

# ln -s i\
#   ~/dehydrated/accounts/aHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2RpcmVjdG9yeQo/account_key.pem \
#   ~/.ssh/le-33935398.key

- hosts: localhost
  gather_facts: no
  vars:
    acme_account_key_src: '~/.ssh/le-33935398.key'
    domain: "d35.ru"
    server_hostname: "ix.{{ domain }}"
    server_pk_path: "~/.ssh/https/ix.pem"
    server_csr_path: "vars/{{ server_hostname }}.csr"
    server_certificate: "vars/{{ server_hostname }}.pem"
  tasks:
    - include: tasks/acme-facts-kfile.yml
    - name: Webserver Private key (always re-new)
      openssl_privatekey:
        path: "{{ server_pk_path }}"
        force: yes  # re-generate if exists?
        mode: 0600

    - name: Prepare CSR
      openssl_csr:
        path: "{{ server_csr_path }}"
        privatekey_path: "{{ server_pk_path }}"
        common_name: "{{ server_hostname }}"
        subject_alt_name:
          - "DNS:{{ server_hostname }}"
          - "DNS:www.{{ domain }}"
      register: r

    # https://docs.ansible.com/ansible/2.[67]/modules/acme_certificate_module.html
    - acme_certificate:
        acme_version: 2
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        account_key_src: "{{ acme_account_key_src }}"
        account_email: mz0@outlook.com
        csr: "{{ server_csr_path }}"
        challenge: dns-01
        dest: "vars/{{ server_hostname }}.crt"
      register: acme_data

    - name: Ensure challenge is addressed on DNS nameserver
      cloudflare_dns:
        zone: d35.ru
        account_api_token: "{{ lookup('file', '~/.ssh/cloudflare/d35z') }}"
        account_email: d35z@mail.ru
        type: TXT
        ttl: 120
        state: present
        record: "{{ item.value['dns-01'].record }}"
        value:  "{{ item.value['dns-01'].resource_value }}"
      with_dict: "{{acme_data.challenge_data}}"
      when: acme_data is changed

    - name: Let the challenge be validated and retrieve the cert and intermediate certificate
      acme_certificate:
        acme_version: 2
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        account_key_src: "{{ acme_account_key_src }}"
        csr: "{{ server_csr_path }}"
        challenge: dns-01
        dest: "vars/{{ server_hostname }}.crt"
        remaining_days: 60
        data: "{{ acme_data }}"
      register: le_cert

    - name: Clean-up challenge response
      cloudflare_dns:
        zone: d35.ru
        account_api_token: "{{ lookup('file', '~/.ssh/cloudflare/d35z') }}"
        account_email: d35z@mail.ru
        state: absent
        record: "{{ item.value['dns-01'].record }}"
      with_dict: "{{acme_data.challenge_data}}"
      when: acme_data is changed and not le_cert.failed
