- name: Add repos
  become: yes
  apt_repository: repo={{ item }} filename="EMP"
  loop: "{{ repo_list }}"
  register: add_repos

- name: Add repo keys
  become: yes
  apt_key: id={{ item }} keyserver='keyserver.ubuntu.com'
  loop: "{{ repo_keys }}"
  register: add_repokeys

- name: Add EMP-packages
  become: yes
  apt: pkg={{ emp_pkgs }} install_recommends=no update_cache=yes
  register: emp_install
