- name: Pick random password for DBroot
  set_fact: db_password={{ lookup('password', '/dev/null length=16') }} db_user="root"

- name: Set DBroot password (if empty)
  shell: mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('{{db_password}}') WHERE User='{{db_user}}';  FLUSH PRIVILEGES;"

- name: Save DBroot password to ~root/.my.cnf (if it was empty)
  become: yes
  template: src=my-cnf.j2 dest=/root/.my.cnf
