- name: check presence of /dev/vg/lv_swap
  shell: "if [ -b /dev/vg/lv_swap ]; then echo vg-lv_swap; fi"
  register: res
  changed_when: no

- name: Set flag if swap space was found
  set_fact: swap_allocated=yes
  when: res.stdout == "vg-lv_swap"

- name: Set skip flag when swap space not found
  set_fact: swap_allocated=no
  when: res.stdout != "vg-lv_swap"

- name: turn-off swap
  become: yes
  shell: "if [ -b /dev/vg/lv_swap ]; then /sbin/swapoff /dev/mapper/vg-lv_swap; fi"
  when: swap_allocated

- name: delete swap from /etc/fstab
  become: yes
  lineinfile: dest=/etc/fstab line="/dev/mapper/vg-lv_swap none            swap    sw              0       0" state=absent
  when: swap_allocated

- name: delete LV
  become: yes
  shell: "/sbin/lvremove -f /dev/vg/lv_swap"
  when: swap_allocated

- name: extend LV lv_root
  become: yes
  shell: "/sbin/lvextend -l +100%FREE /dev/vg/lv_root"
  when: swap_allocated

- name: extend lv_root's / filesystem
  become: yes
  shell: "/sbin/resize2fs /dev/vg/lv_root"
  when: swap_allocated
