- name: Install updates
  apt: upgrade=dist update_cache=yes

- name: Install essential packages
  apt:
    update_cache: yes
    pkg: ['sudo','openssh-server','openssh-sftp-server','openntpd','apt-transport-https']
    install_recommends: no

- name: Ensure service is enabled and running
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - openntpd
