- fail: msg="root_ssh_pk is not defined!"
  when: root_ssh_pk is not defined

- name: Check SSH port 22
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    connect_timeout: 30
    timeout: 15
  delegate_to: localhost
  ignore_errors: yes
  register: default_ssh

- name: Set ansible_port 22 if open
  set_fact: ansible_port=22
  when: default_ssh is defined and
        default_ssh.state is defined and
        default_ssh.state == 'started'

- name: Check host connection
  ping:

- name: Add ssh pubkey to ~root/.ssh/authorized_keys
  become: yes
  authorized_key: user=root state=present key={{ root_ssh_pk }}

- name: disable root password
  become: yes
  user: name=root password='!'
