
##### TODO consider resetting ansible_port in launch-/relaunch- playbooks ###
- name: Check port 22 is open
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    connect_timeout: 30
    timeout: "{{ wait_ssh }}"    # delay start for a new DO host
  delegate_to: localhost
  ignore_errors: yes
  register: default_ssh

- name: Use ansible_port=22 if open
  set_fact: ansible_port=22      # if static inventory has the desired port we should reset that if we re-create VM
  when: default_ssh is defined and
        default_ssh.state is defined and
        default_ssh.state == 'started'
##### TODO consider resetting ansible_port in launch-/relaunch- playbooks ###

- name: Confirm host connection works
  ping:

- name: Replace systemd (stage 1 - install sysvinit-core etc.)
  become: yes
  apt:
    update_cache: no
    pkg: ['sysvinit-core','sysvinit-utils']
    install_recommends: no
  register: initsystem

- name: Reboot to replace systemd (ETA 23 seconds) if sysvinit just installed
  become: yes
  reboot: # Ansible 2.7 required
  when: initsystem is changed

- name: Replace systemd (stage 2 - uninstall systemd)
  become: yes
  apt:
    state: absent
    purge: yes
    autoremove: yes
    autoclean: yes
    pkg: ['systemd']
