- name: Purge unused packages
  become: yes
  apt:
    name: "{{ trim_list }}"
    state: absent
    purge: yes
    install_recommends: no
    autoremove: yes
    autoclean: yes
  register: uninstall
