---

- name: Create admin user
  user: >
    name="{{ ssh_user }}"
    comment="Administrator account"
    state=present
    groups="{{ ssh_groups }}"
    shell=/bin/bash
    append=yes
    createhome=yes

- name: Copy my ssh pubkey to $USERNAME on the new host
  authorized_key: user="{{ ssh_user }}" key="{{ ssh_pub_key }}"
