# DO droplet settings
vm_name: de.x302.net # DO sets PTR for IPv4 and IPv6 addresses if it's FQDN
dc: fra1             # ams[23] Amsterdam, blr1 Bangalore, nyc[123], ...
size:  s-1vcpu-1gb   # s-1vcpu-2gb, s-2vcpu-2gb, s-1vcpu-3gb, ..., s-32vcpu-192gb.
image: debian-8-x64  # fedora-27-x64, freebsd-11-1-x64-zfs, ubuntu-14-04-x64-do, ...
needIPv6: yes
do_api_token: "{{ lookup('file', '~/.ssh/do/my.apikey') }}"
root_ssh_pk:  "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
wait_minutes:  4     # max wait for VM init, usually it's under 2 minutes
wait_ssh:     25     # max wait for SSH to come up

# override default/main.yml
ssh_set_port: 2222
