ssh_set_port: 8022

# Create admin user
ssh_user: "{{ lookup('env', 'USERNAME') }}"
ssh_groups: "sudo"
ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

swapfile_location: /swapfile
swapfile_size: 1025M
swapfile_swappiness: 10
swapfile_vfs_cache_pressure: 50
